version: '2'
services:
  db:
    image: mysql
    ports:
      - "33333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'internetprodaja'
      MYSQL_PASSWORD: 'internetprodaja'
      MYSQL_DATABASE: 'internetprodaja'
