SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE article;
TRUNCATE TABLE customer;
TRUNCATE TABLE orderfact;
TRUNCATE TABLE offerfact;
TRUNCATE TABLE ordertime;
TRUNCATE TABLE offertime;
TRUNCATE TABLE price;
TRUNCATE TABLE seller;

SET FOREIGN_KEY_CHECKS=1;
